<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-14T23:18:42 IST" name="DLAD CRM Automation Test Suite" finished-at="2024-07-14T23:19:33 IST" duration-ms="50583">
    <groups>
    </groups>
    <test started-at="2024-07-14T23:18:42 IST" name="DLAD QA Testing" finished-at="2024-07-14T23:19:33 IST" duration-ms="50583">
      <class name="com.dlad.qa.testcases.Home">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:18:43 IST" name="beforeMethod" finished-at="2024-07-14T23:19:01 IST" duration-ms="17838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyUserRedirectsToTheHomePage()[pri:1, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:01 IST" name="verifyUserRedirectsToTheHomePage" finished-at="2024-07-14T23:19:01 IST" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserRedirectsToTheHomePage -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:01 IST" name="afterMethod" finished-at="2024-07-14T23:19:01 IST" duration-ms="384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:01 IST" name="beforeMethod" finished-at="2024-07-14T23:19:17 IST" duration-ms="15846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyDisplayTheHomePageCardNames()[pri:2, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:17 IST" name="verifyDisplayTheHomePageCardNames" finished-at="2024-07-14T23:19:17 IST" duration-ms="202" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [BP Activitie] but found [BP Activities]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [BP Activitie] but found [BP Activities]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.dlad.qa.testcases.Home.verifyDisplayTheHomePageCardNames(Home.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDisplayTheHomePageCardNames -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:18 IST" name="afterMethod" finished-at="2024-07-14T23:19:18 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:18 IST" name="beforeMethod" finished-at="2024-07-14T23:19:32 IST" duration-ms="13916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyDisplayTheHomePageCardCounts()[pri:3, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:32 IST" name="verifyDisplayTheHomePageCardCounts" finished-at="2024-07-14T23:19:32 IST" duration-ms="432" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [BP Activitie] but found [BP Activities]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [BP Activitie] but found [BP Activities]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.dlad.qa.testcases.Home.verifyDisplayTheHomePageCardCounts(Home.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDisplayTheHomePageCardCounts -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.dlad.qa.testcases.Home@7f36662c]" started-at="2024-07-14T23:19:32 IST" name="afterMethod" finished-at="2024-07-14T23:19:33 IST" duration-ms="362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.dlad.qa.testcases.Home -->
    </test> <!-- DLAD QA Testing -->
  </suite> <!-- DLAD CRM Automation Test Suite -->
</testng-results>
